//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maraton
    {
        public Maraton()
        {
            this.Maraton_Usuario = new HashSet<Maraton_Usuario>();
        }
    
        public int ID { get; set; }
        public string Nombre { get; set; }
        public int Cant_Participantes { get; set; }
        public string Lugar_Salida { get; set; }
        public int Cant_Lista_Espera { get; set; }
        public decimal Premio_Uno { get; set; }
        public decimal Premio_Dos { get; set; }
        public decimal Premio_Tres { get; set; }
    
        public virtual ICollection<Maraton_Usuario> Maraton_Usuario { get; set; }
    }
}
