//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maraton_Usuario
    {
        public int MaratonID { get; set; }
        public int UsuarioID { get; set; }
        public bool Lista_Espera { get; set; }
        public Nullable<System.TimeSpan> Tiempo_Llegada { get; set; }
        public Nullable<bool> Presente { get; set; }
        public Nullable<bool> Abandono { get; set; }
    
        public virtual Maraton Maraton { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
