//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDeDatos.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maraton_Usuario
    {
        public int MaratonID { get; set; }
        public int UsuarioID { get; set; }
        public bool Lista_Espera { get; set; }
        public Nullable<System.DateTime> Tiempo_Llegada { get; set; }
        public bool Presente { get; set; }
        public bool Abandono { get; set; }
    
        public virtual Maraton Maraton { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
